### ISSUE TITLE
Execute Interface - User Comments & Suggestions

### ISSUE THREAD

**Issue by jeog** [jeog/TDAmeritradeAPI#1]
Use this issue to comment on and make suggestions about the upcoming interface for order execution and management. [See the provisional README_EXECUTE.md](../blob/master/README_EXECUTE.md).

**Comment by brw59** [comment]
Two suggestions:
1) It'd be nice to have a one-time use file to generate the credentials file from either the 'code' or the already acquired credentials. Something like this is good enough to make the file using python, though it'd be better if the details were prompted rather than hard coded probably:

```
from tdma_api import auth     # authorization methods and objects
from tdma_api import get      # 'getter' objects and utilities
from tdma_api import stream   # 'streaming' class and subscriptions
from tdma_api import execute  # order objects, builders and execution calls

# code = "<code>" # if you don't have an access code already ... could set it up to generate the credentials from 'code' instead
client_id = "<client_id>"

acc = "<access_code>"
ref = "<refresh_token>"
creds = auth.Credentials(acc.encode('utf-8'), ref.encode('utf-8'), 1, client_id.encode('utf-8'))

auth.store_credentials("key.txt", "password", creds)
```


2) My second suggestion is to show what the request was if it fails due to a permission issue. Running the test file (in python3) it had an error half way through, it'd be nice to see what I was trying to query that I don't have permission for yet without looking through my code to try and find it. (It's easy enough to find the location in python, though I suspect c++ works the same way, in which it wouldn't be as easy to find the query that permissions aren't granted for. It would also be nice to enable a flag somewhere to ignore the permission issue, and move on, rather than erring out.

```
+++++++++++++++++++++++++++++
+ test_account_info_getters +
+++++++++++++++++++++++++++++ 

error response: 403
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 72, in test
    func(*args)
  File "test.py", line 509, in test_account_info_getters
    j = Get(g)
  File "test.py", line 57, in Get
    return getter.get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tdma_api/get.py", line 227, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tdma_api/clib.py", line 155, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tdma_api/clib.py", line 122, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: forbidden: {
  "error" : "You don't have permission to access this resource."
}(response code =403) [error code: 103, line: 98, file: ../src/tdma_connect.cpp]
```

**Comment by jeog** [comment]
1) Initially the idea was to keep everything super low-level, basically just wrap their API, to let users manage auth however they want. However, making it easier to build the Credentials object is probably a good idea. It is implemented as a struct w/ public members so should be easy enough to build. Another thing to keep in mind is the 'epoch_sec_token_expiration' field, which the library will check against the system clock and throw if gets < 1 day until exp.

2) I didn't want to get to deep into managing/handling those errors because TDMA's API is still in flux and it would require parsing returned json/strings for details. I had an issue earlier where I was accounting for a bug in one of their responses; then they fixed it, breaking the lib. Thought it was best to keep error handling as simple and generic as possible until I was sure of exactly what was coming back from them.
